from .parser_prompt import RESUME_PARSER_SYSTEM_PROMPT
from .skill_prompt import SKILL_EXTRACTOR_SYSTEM_PROMPT
from .experience_prompt import EXPERIENCE_ANALYZER_SYSTEM_PROMPT
from .jd_prompt import JD_SKILL_EXTRACTOR_SYSTEM_PROMPT
from .gap_prompt import GAP_ANALYSIS_SYSTEM_PROMPT
from .ats_prompt import ATS_SCORING_SYSTEM_PROMPT
from .rewrite_prompt import RESUME_REWRITER_SYSTEM_PROMPT
from .interview_prompt import INTERVIEW_GENERATOR_SYSTEM_PROMPT
from .report_prompt import CAREER_REPORT_SYSTEM_PROMPT

__all__ = [
    "RESUME_PARSER_SYSTEM_PROMPT",
    "SKILL_EXTRACTOR_SYSTEM_PROMPT",
    "EXPERIENCE_ANALYZER_SYSTEM_PROMPT",
    "JD_SKILL_EXTRACTOR_SYSTEM_PROMPT",
    "GAP_ANALYSIS_SYSTEM_PROMPT",
    "ATS_SCORING_SYSTEM_PROMPT",
    "RESUME_REWRITER_SYSTEM_PROMPT",
    "INTERVIEW_GENERATOR_SYSTEM_PROMPT",
    "CAREER_REPORT_SYSTEM_PROMPT",
]
